### ISSUE TITLE
Error on file view creation

### ISSUE THREAD

**Issue by CKLFP** [ctf0/laravel-goto-view#2]
Hi,
I got an error message when I click in a view, and it doesn't exist, so the extension tries to create one... and then it pops the error message :(
![Captura de ecrã 2021-02-17 212542](https://user-images.githubusercontent.com/5192692/108270277-274f2300-7167-11eb-8078-188e015d0fad.png).

Can you help me?
Thanks

**Comment by ctf0** [comment]
sorry, i just saw this, this probably related to windows & unix directoy seperator.

can u give me some steps to reproduce ?

**Comment by ChrisSchuessler** [comment]
Hi there,

same problem here. Clicking with CTRL - LeftMouseClick tries to create the non existing view but breaks with information 'Laravel Goto View:"" created' and 'Unable to open '': File is a directory. Any ideas?

Thanks in advance

Chris

![image](https://user-images.githubusercontent.com/100433213/162530853-adf89229-90a9-4829-bad1-4d5424902ecc.png)

**Comment by ctf0** [comment]
@ChrisSchuessler 

can u give steps to reproduce

**Comment by ChrisSchuessler** [comment]
> @ChrisSchuessler
> 
> can u give steps to reproduce

Yes of course:

![image](https://user-images.githubusercontent.com/100433213/165389918-5832c472-cfd7-439c-9327-aeb704e16f59.png)

![image](https://user-images.githubusercontent.com/100433213/165389996-b1e53114-fee2-4bd5-abc4-3408ac47d9fc.png)

Result:
![image](https://user-images.githubusercontent.com/100433213/165390060-f7f2a946-f149-428d-acf7-d781e886a23a.png)


Here are my user settings json:
![image](https://user-images.githubusercontent.com/100433213/165390704-35be4cc2-4c5a-4480-858b-7af56e5e9372.png)

I didn't change the default Regex: (?<=view\(['"]|View::make\(['"]|@include\(['"]|@extends\(['"]|@component\(['"]|Inertia::render\(['"]|\<)(\<x-|\<livewire:|[^'" \/>]+)

**Comment by ctf0** [comment]
@ChrisSchuessler actually the config setting is not related to this package https://github.com/ctf0/laravel-goto-view/blob/a8b0f055032938a0082e111a413d74e607e2092a/package.json#L61

also on which OS does this happen ?

**Comment by ChrisSchuessler** [comment]
> @ChrisSchuessler actually the config setting is not related to this package
> 
> https://github.com/ctf0/laravel-goto-view/blob/a8b0f055032938a0082e111a413d74e607e2092a/package.json#L61
> 
> also on which OS does this happen ?

Oh, I'm sorry, my fault. I had installed the "Laravel got view" from "codingyu" too. But:
After uninstalling both extensions and reinstalling your extension the behaviour/result is the same as described from me above.

I'm on a Windows 10 computer and i didn't change anything in the settings of your extension. Maybe I have to change the "Default Path"?

Here are the settings:
![image](https://user-images.githubusercontent.com/100433213/165563936-fac68c97-fef1-4a0d-aa05-9f48e7d3fcf3.png)

![image](https://user-images.githubusercontent.com/100433213/165564018-2843f3d1-b90d-4b56-a1dc-f0b0571747d5.png)

![image](https://user-images.githubusercontent.com/100433213/165564081-3bc66329-6a1e-4e74-8282-2f1e7b942fb2.png)

**Comment by ctf0** [comment]
yes, try to change all the paths in the extension settings from using `/` to `\` and see if it helps

**Comment by TalionOak** [comment]
not fixed, same error with ``\``

Windows 10 too

**Comment by ctf0** [comment]
sadly i dont use windows, can someone debug the issue or make a PR with a fix ?
