### ISSUE TITLE
Remove "Copy File Path" button from view ?

### ISSUE THREAD

**Issue by WebCimes** [ctf0/laravel-goto-view#6]
Hi,

There is a way to remove the "Copy File Path" button from blade view ?

I doesn't need it and I think maybe it will be nice if we can remove it with an option (I have watch in the parameter but I didn't found an option for this).

Thanks for your plugin :)

**Comment by ctf0** [comment]
u can use the config key `showCodeLens` to disable/enable the code lens extension wide

**Comment by WebCimes** [comment]
Thanks
