### ISSUE TITLE
Support for mult-iline function call

### ISSUE THREAD

**Issue by solis-eduardo** [ctf0/laravel-goto-view#7]
Is it possible to allow quick jump to a view referenced in a multi-line function call?

Example:
```PHP
return view(
    'role.index',
    compact([
        'settings',
        'roles',
        'projects',
    ])
);
```

**Comment by ctf0** [comment]
can be done, we use regex for searching https://github.com/ctf0/laravel-goto-view/blob/b5a8c53e66345e7afdfc5b2ae6ca511032fbd590/src/providers/LinkProvider.ts#L31

you can make a PR with the changes needed as am a bit busy atm
